In [14]:
import re
import pandas as pd

In [15]:
entry_df = pd.read_csv("incu_ocr_bll_matching_v1.4.csv", index_col=0)

In [16]:
entry_df.shape

(8774, 10)

### Explore Another copy variants

In [17]:
copy_re = re.compile(r"Another \S*")
anothers = entry_df["entry_text"].apply(lambda x: copy_re.search(x))
copy_variants = sorted(list(set(anothers.apply(lambda x: x.group() if x else None).dropna())))
copy_variants

['Another (crown',
 'Another calendar',
 'Another calligraphic',
 'Another cancelled',
 'Another closely',
 'Another compartment',
 'Another copy',
 'Another copy,',
 'Another copy.',
 'Another cut',
 'Another edition',
 'Another edition,',
 'Another edition.',
 'Another fragment,',
 'Another full-page',
 'Another issue',
 'Another issue,',
 'Another issue.',
 'Another metrical',
 'Another reading.',
 'Another recension',
 'Another setting',
 'Another setting-up',
 'Another version']

In [18]:
x = 2
print(copy_variants[x])
entry_df[entry_df["entry_text"].str.contains(copy_variants[x])]

Another calligraphic

,xmls,vol,col_pages,vol_entry_num,shelfmark,bll01_shelfmark,record_id,uncaptured_sm,entry_text,entry_text_spaces
7681,"['J_2704_aa_30_8_0260_4', 'J_2704_aa_30_8_0261...",8,"4-36, 4-37,",463,IA. 40393,IA. 40393,1151969,0.0,DATES. Tréperel is not known to have printed a...,DATES. Tréperel is not known to have printed a...



All the matches of the "Another \S*" regex with statement as to whether consists of actual 'Another edition' information.

'Another (crown': Not valid, referring to watermarks in the text  
'Another calendar': Not valid, referring to calendars in the work  
'Another calligraphic': Not valid, referring to calligraphic letters  
'Another cancelled': Valid, has it's own Proctor # and copy specific info. There's also a copy before this that's just "A cancelled copy", but there's only one occurence of this.  
'A cancelled': Valid, see above entry.  
'Another closely': Not valid, describes another edition that's similar  
'Another compartment': Not valid, part of the information rather than about  another copy
'Another copy': Valid  
'Another copy,': Subset of Another copy  
'Another copy.': Subset of Another copy  
'Another cut': Not valid  
'Another edition': Valid  
'Another edition,': Subset  
'Another edition.': Subset  
'Another fragment,': Valid  
'Another full-page': Not valid  
'Another issue': Valid  
'Another issue,': Subset  
'Another issue.': Subset  
'Another metrical': Not valid  
'Another reading.': Not valid  
'Another recension': Not valid  
'Another setting': Not valid  
'Another setting-up': Subset  
'Another version: Not valid

In [19]:
valid_copy_variants = ["Another cancelled", "A cancelled", "Another copy", "Another edition", "Another fragment", "Another issue"]

In [24]:
entry_contains_variant = []
for variant in valid_copy_variants:
    entry_contains_variant.append(entry_df["entry_text"].str.count(variant).rename(variant))

In [29]:
another_counts_df = pd.concat(entry_contains_variant, axis=1)
another_counts_df

,Another cancelled,A cancelled,Another copy,Another edition,Another fragment,Another issue
0,0,0,0,3,0,0
1,0,0,0,0,0,0
2,0,0,0,2,0,0
3,0,0,0,1,0,0
4,0,0,0,0,0,0
...,...,...,...,...,...,...
8769,0,0,0,0,0,0
8770,0,0,0,0,0,0
8771,0,0,0,0,0,0
8772,0,0,0,0,0,0
8773,0,0,0,0,0,0

In [26]:
pd.concat(entry_contains_variant, axis=1).sum()

Another cancelled       1
A cancelled             1
Another copy         1112
Another edition        25
Another fragment        1
Another issue          39
dtype: int64

In [31]:
entry_df[another_counts_df["Another cancelled"].astype(bool)]

,xmls,vol,col_pages,vol_entry_num,shelfmark,bll01_shelfmark,record_id,uncaptured_sm,entry_text,entry_text_spaces
30,"['J_2704_aa_30_1_0054_2', 'J_2704_aa_30_1_0055...",1,"2-10, 2-11,",30,IC. 77,IC. 77,321460,0.0,"Psalterium ad honorem\nSALTERIUM.\n*29 August,...","Psalterium ad honorem SALTERIUM. *29 August, 1..."

In [35]:
entry_df[another_counts_df["Another issue"].astype(bool)].sample(1)

,xmls,vol,col_pages,vol_entry_num,shelfmark,bll01_shelfmark,record_id,uncaptured_sm,entry_text,entry_text_spaces
7839,['J_2704_aa_30_8_0316_2'],8,"2-154,",621,IA. 40970,IA. 40970,2189205,0.0,HORAE. Heures à l'usage de Rome.\n*14 November...,"HORAE. Heures à l'usage de Rome. *14 November,..."

In [36]:
entry_df[another_counts_df["Another edition"].astype(bool)].sample(1)

,xmls,vol,col_pages,vol_entry_num,shelfmark,bll01_shelfmark,record_id,uncaptured_sm,entry_text,entry_text_spaces
8051,['J_2704_aa_30_8_0410_2'],8,"2-203,",833,"IA. 42066, 42069, 42070",NaN,NaN,NaN,"From the Old Library.\nMAILLARD, OLIVIER. Serm...","From the Old Library. MAILLARD, OLIVIER. Sermo..."

In [37]:
entry_df[another_counts_df["Another copy"].astype(bool)].sample(7)

,xmls,vol,col_pages,vol_entry_num,shelfmark,bll01_shelfmark,record_id,uncaptured_sm,entry_text,entry_text_spaces
6427,"['J_2704_aa_30_6_0313_4', 'J_2704_aa_30_6_0314...",6,"4-106, 2-151,",914,IB. 29314,IB. 29314,243206,0.0,ANTONIUS [BECCADELLII PANORMITA.\nEpistolae fa...,ANTONIUS [BECCADELLII PANORMITA. Epistolae fam...
2535,['J_2704_aa_30_3_0054_2'],3,"2-3,",21,IA. 11552,IA. 11552,753090,0.0,AEGIDIUSTCOLUMNAJROMANUS. Theore¬\nmata de ess...,AEGIDIUSTCOLUMNAJROMANUS. Theore¬ mata de esse...
3305,['J_2704_aa_30_4_050_2'],4,"2-21,",70,IB. 17355,IB. 17355,002993011;000943360;001663519;003186138,0.0,26\nDOUBTFUL.\nPRISCIANUS. Opera.\nUndated.\n2...,26 DOUBTFUL. PRISCIANUS. Opera. Undated. 2°. I...
851,"['J_2704_aa_30_1_0251_4', 'J_2704_aa_30_1_0252...",1,"4-50, 4-51,",851,G. 9318,NaN,NaN,NaN,"CICERO, MARCUS TULLIUS. Cato Major,\nsiue de s...","CICERO, MARCUS TULLIUS. Cato Major, siue de se..."
5967,['J_2704_aa_30_6_0171_2'],6,"2-74,",454,IB. 25958,IB. 25958,3749204,0.0,VALERIUS MAXIMUS.\nFacta et dicta\nmemorabilia...,VALERIUS MAXIMUS. Facta et dicta memorabilia. ...
3566,"['J_2704_aa_30_4_109_2', 'J_2704_aa_30_4_110_2']",4,"2-58, 2-59,",331,IA. 18423,IA. 18423,2386962,0.0,"MARLIANUS, JOANNES FRANCISCI. Oratio\nhabita a...","MARLIANUS, JOANNES FRANCISCI. Oratio habita ap..."
341,['J_2704_aa_30_1_0134_2'],1,"2-72,",341,IB. 1323,IB. 1323,3144232,0.0,"GRITSCH, JoHANNEs. Quadragesimale.\n9 October,...","GRITSCH, JoHANNEs. Quadragesimale. 9 October, ..."

Ground truth columns = ['Shelfmark', 'Date 1', 'Name', 'Title', 'Place of publication',
       'Publisher', 'Date of publication in Arabic or Roman numerals',
       'Extent', 'Dimensions', 'General notes', 'Bibliography etc. note',
       'Method of acquisition']

Ground truth column IDs = ["A", "E", "Q", "U", "AB", "AC", "AD", "AH", "AJ", "AQ", "AR", "CM"]

In [ ]:
print(entry_df.loc[5400, "entry_text"])

THEOCRITUS. EiSvANta. (With other tracts)
February, 14956.
r. TITLE: TAAE ENEETI'ENTHIAETHIBIBAOL.
Oeonoiro id  a  ra
... (l. 18) Haec insunt in hoc libro. Theocriti Ecloga
triginta. Genus Theocriti & de inuentione bucolicorum.
Catonis Romani sententiae paræneticae distichi.e
tentiae septem sapientum. De Inuidia. Theognidis
megarensis siculi sententiae elegiacae. Sententiae mono¬
stichi per Capita ex uariis poetis. Aurea Carmina
Pythagoroe. Phocylidae Poema admonitorium. Carmina
Sibyllæ erythroea de Christo lesu domino nro. Differetia
uocis. Hesiodi Theogonia. Eiusdem scutum Herculis.
Eiusdem georgicon libri duo. 1408. COLOPHON : Im¬
pressum Venetiis characteribus ac studio Aldi Manuc
Ro mani cum gratia &c. . M. CCCC. XCV. Mense febru¬
ario. 1406. TITLE: In hoc volumine continentur haec
Hesiodi Ascraei poetae Theogonia. hoc est de generatione
deoru opusculum. Eiusde Aspis. hoc est de scuto
Herculis opusculum. Eiusdem Georgicorum libri duo dicti
Erga & Himerae. idest opera & dies.
Folio. A-A-A-D8 E-E-O-G'; AA aa-AA-808 EE-se zZ-((10; a:a 8-b8
yclo; oedee. 140 leaves. 32 : 30 lines, 219X 103 (110) mm.
Types: 146 Gk.; 114 R., title on 12; 83 R., text on 1b colophon.
title on 140°. Woodcut capitals and borders. Initials of inter¬
locutors set out. Catchwords, except in a-a-y.c. Hain '15477.
1a title; 1°, Aldus Baptistae Guarino s. p. d.; 22, Theocritus ;
50%, blank: 51° Theognis; 892 Disticha of Dionysius Cato, trans¬
lated into Greek hexameters by Maximus Planudes; 952, sentences
of the Seven Sages; 97°, repi g6óvov : 98a register of quires A-A¬
G; 98°, blank; 99e, Hotéôov Oeoyovia; 125° Hotóôov Epya xai
juépat ; 139, register of quires aa-ce; 140e, colophon; 140°, title.
The order of the contents here given follows the quiring. The
title, by putting Cato, the Seven Sages, and De inuidia immediately
after Theocritus, involves the precedence of quire Zz-(( over quires
AA aa-EE-ee The register ignores quires AA-aa-zZmp.
In his prefatory letter on 1b Aldus speaks of Apollonius Gram¬
maticus (whose work forms part of the Gaza volume) as already
printed.
On 43° (Z-F 52) the text of the idyl METAPA TYNH HPAKAEOY2
is interrupted after l. 13 (ExérAtos... d), the place of the
remainder being taken by l. 35-end of the EIIITAGIOZ BIONO2,
which has already appeared in its right place on E-E 22, &c. On
this follows the idyl AIO2KOYPOI (near end of Z-F 6b), from which
Il. 45-91 are omitted on 0-G1b then that here entitled MI2ON
bIAEONTA [i.e. ’Epagris), 2YPITE, EIZ NEKPON AAQNIN, TENO2
OEOKPITOY and HEPI EYPEZEQZ TON BOYKOAIKON.
Type 114 R. here looks fresh, but has no accents.
Venduntur non minoris marcellis octo' (Aldus's list of 1498).
300 x 205 mm. Red ms. rules round title.
King George III's copy (C. 1. c. 2).
IB. 24404.
IA. 24412. Another copy.
305 x 207 mm. Red ms. rules round text throughout.
The first two leaves are made up.
Cracherode copy, with date 1789. IB. 24405a.
Another copy.
319X212 mm. Quire ZZ.( (Cato, etc.) is bound
before quire AA. aa. On a fly-leaf is written: WS. 1804.
Grenville copy (G. 8680).
IB. 24405.
Another copy.
298 x 205 mm. Quire ZZ.Cbound before quire AA.aa.
Early Italian stamped leather.
IB. 24402
Bought.
Another copy, wanting Theocritus.
318X 218 mm. Bound thus: quires ôd, ee, a.a-y.c,
AAaa-ZZ-g. Quires ôd, ee (Works and Days) have
copious ms. notes by Demetrius Chalcondylas. Or
yc 10b is written: Antonij Seripandi ex Iani Parrhasij
testamento. With the armorial bookplate of — Smith.
IB. 24403.
Bought in January, 1855.
Another issue, with part of quire Z.F and the
whole of quire O-G reprinted.
In this issue the omitted text of the METAPA beginning Hé rivos
goôv, appears in its right place (432, &c.) and is followed by the
o on O-G 1e the Epaoris on 0-G 4°, the yg on 0-G62
printed within a goblet-shaped woodcut figure, and the EIZ NEKPON
AAONIN on the last page of the quire. These alterations involved
the reprinting of both quires with the exception of the inner sheet
of Z-F.
310X 209 mm. Red ms. rules round each page of
text. Bound in blue-grey morocco by Bradel l'aîné,
quire ZZ'g appearing before quire AA aa.
Grenville copy (G. 8681).
IB. 24408.
Another copy.
277X 163 mm. With the book-label of Dr. Charles
Burney. The second leaf is mutilated, the text being
made good in pen-and-ink facsimile.
Bought.
IB. 24407.
Another copy.
282X 197 mm. Imperfect, wanting sheet Z'F 3.
Quire ZZ'g is bound before quire AA'aa. Bound in
red morocco, stamped with the cypher of King Charles II.
IB. 24406.

In [ ]:
entry_df["entry_text"].str.count("Another copy").idxmax()

5400

In [ ]:
entry_df["match"].dropna().apply(lambda x: x.group()).unique()

array(['Another edition.', 'Another edition,', 'Another issue.',
       'Another copy', 'Another copy.', 'Another cancelled',
       'Another issue,', 'Another copy,', 'Another issue',
       'Another calendar', 'Another fragment,', 'Another setting-up',
       'Another edition', 'Another (crown', 'Another metrical',
       'Another reading.', 'Another cut', 'Another calligraphic',
       'Another setting', 'Another closely', 'Another full-page',
       'Another version', 'Another recension', 'Another compartment'],
      dtype=object)

All the matches of the "Another \S*" regex with statement as to whether consists of actual 'Another edition' information.

'Another (crown': Not valid, referring to watermarks in the text  
'Another calendar': Not valid, referring to calendars in the work  
'Another calligraphic': Not valid, referring to calligraphic letters  
'Another cancelled': Valid, has it's own Proctor # and copy specific info. There's also a copy before this that's just "A cancelled copy", but there's only one occurence of this.  
'A cancelled': Valid, see above entry.  
'Another closely': Not valid, describes another edition that's similar  
'Another compartment': Not valid, part of the information rather than about another copy  
'Another copy': Valid  
'Another copy,': Subset of Another copy  
'Another copy.': Subset of Another copy  
'Another cut': Not valid  
'Another edition': Valid  
'Another edition,': Subset  
'Another edition.': Subset  
'Another fragment,': Valid  
'Another full-page': Not valid  
'Another issue': Valid  
'Another issue,': Subset  
'Another issue.': Subset  
'Another metrical': Not valid  
'Another reading.': Not valid  
'Another recension': Not valid  
'Another setting': Not valid  
'Another setting-up': Subset  
'Another version: Not valid

In [ ]:
# Important 'Another' variants

another_variants = [
    'Another cancelled',
    'A cancelled',
    'Another copy',
    'Another edition',
    'Another fragment,',
    'Another issue'
]

Having a leading shelfmark is highly indicative of an 'Another copy' entry actually being another copy. Of course this relies on the shelfmark detection being accurate. In some cases this isn't so, see analysis below for efforts to improve Issac's shelfmark finding.

In [ ]:
# TODO some of the shelfmarks are absent - instead the Another copy has it's location listed as "Print room"
# work out what to do with this

### Function Development

In [ ]:
def extract_another_copy(row):
    """

    :return:
    """
    another_variants = [
        'Another cancelled',
        'A cancelled',
        'Another copy',
        'Another edition',
        'Another fragment,',
        'Another issue'
    ]

    match = []
    for v in another_variants:
        p = re.compile(v)
        m = p.finditer(row)
        if m:
            match += m

    if match:
        return match
    else:
        return None